import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SideMenu from "@/components/sideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} flex flex-col w-full h-full bg-zinc-900`}
        >
          <div className="flex flex-row w-full h-full">
            <SideMenu />
            <main className="flex-grow p-4">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
